version: '3.9'

services:
  db:
    image: postgres
    container_name: untappd-postgres-db
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./roles_permissions_gen.sh:/docker-entrypoint-initdb.d/roles_permissions_gen.sh
    environment:
      POSTGRES_DB: "untappd_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    entrypoint: > 
      /bin/bash -c "chmod a+x /docker-entrypoint-initdb.d/* &&
      docker-entrypoint.sh postgres"

  flyway:
    image: 'flyway/flyway:7.7'
    container_name: untappd-flyway
    depends_on:
      - db
    command: ["migrate"]
    volumes:
    - type: 'bind'
      source: ./flyway/conf/flyway.conf
      target: /flyway/conf/flyway.conf
      read_only: true
    - type: 'bind'
      source: ./flyway/conf/secret.conf
      target: /flyway/conf/secret.conf
      read_only: true
    - type: 'bind'
      source: ./flyway/sql
      target: /flyway/sql
      read_only: true
    environment:
      FLYWAY_CONFIG_FILES: /flyway/conf/flyway.conf,/flyway/conf/secret.conf

  db-init:
    image: python:3.8-buster
    container_name: db-init
    depends_on:
      flyway:
        condition: service_completed_successfully
    volumes:
      - .:/src
    environment:
      USERS_NUM: 1000000
      GENERATE_WITH_CLEANING: "false"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "untappd_db"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: 5432
      POSTGRES_CONNECT_RETRIES: 5
      POSTGRES_CONNECT_INTERVAL: 3 # in seconds
      CRYPT_KEY: "yG3BfC0EZQRuYoJvQkHmP4zSpkTAqs9b"
      RANDOM_SEED: 123
    command: > 
      /bin/bash -c "
      pip install psycopg2-binary Faker &&
      python /src/init.py"
    working_dir: /src
    network_mode: host